google_sheets:
  spreadsheet_name: "mydata"
  credentials_path: C:\Workspace\pension\resources\credentials\gcp-nodle-service-account-credential.json

worksheets:
  accounts: "계좌"
  monthly_assets: "월말자산"
  io_history: "입출금"

cache:
  expiration_time: 3600  # 캐시 만료 시간 (초, 1시간)
