data_source:
  type: google_sheets
  spreadsheet_name: mydata

google_sheets:
  credentials_path: D:\Workspace\pension\resources\credentials\gcp-nodle-service-account-credential.json

mysql:
  connection_string: user:password@host:port/database

tables:
  accounts: 계좌
  month_end_assets: 월말자산
