google_sheets:
  spreadsheet_name: "mydata"
  credentials_path: C:\Workspace\pension\resources\credentials\gcp-nodle-service-account-credential.json

worksheets:
  accounts: "계좌"
  month_end_assets: "월말자산"
  pension_portfolio: "연금MP"

cache:
  expiration_time: 3600  # 캐시 만료 시간 (초)
