[tool.poetry]
name = "pension"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
packages = [{include = "pension", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
google-api-python-client = "^2.123.0"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
