[tool.poetry]
name = "pension"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
packages = [{include = "pension", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
gspread = "^6.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
